services:
  rabbitmq:
    build:
      context: ./backend/infraestructure/broker
      dockerfile: Dockerfile
    container_name: susie-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - susie-network

  postgres:
    build:
      context: ./backend/infraestructure/database
      dockerfile: Dockerfile
    container_name: susie-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - susie-network

  redis:
    image: redis:alpine
    container_name: susie-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - susie-network

networks:
  susie-network:
    driver: bridge

volumes:
  rabbitmq_data:
  postgres_data:
  redis_data:
